# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - truetestv1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://truetestv1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_558dbfb96acd43ae9a21c2faa680aec1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fa799726d73c45b0ab82176f698b96b8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: truetestv1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_558dbfb96acd43ae9a21c2faa680aec1 }}/truetestv1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'truetestv1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_15a98cfed40f4affad0f19031013c5b5 }}
        images: 'truetestv1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_558dbfb96acd43ae9a21c2faa680aec1 }}/truetestv1:${{ github.sha }}'