name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run tests
      env:
        AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALGORITHM: ${{ secrets.ALGORITHM }}
        AZURE_APP_INSIGHTS_INSTRUMENTATION_KEY: ${{ secrets.AZURE_APP_INSIGHTS_INSTRUMENTATION_KEY }}
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD_USER }}
        EMAIL: ${{ secrets.EMAIL }}
        MODEL_URL: ${{ secrets.MODEL_URL }}
        TOKENIZER_URL: ${{ secrets.TOKENIZER_URL }}
        EMBEDDING_URL: ${{ secrets.EMBEDDING_URL }}
        MAX_LENGTH: ${{ secrets.MAX_LENGTH }}
        ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      run: |
        source venv/bin/activate
        pytest --maxfail=5 --disable-warnings